version: '3'
services:
  selenium-browser:
    image: selenium/node-chrome:4.3.0-20220706
    container_name: selenium-browser
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
  
  selenium-hub:
    image: selenium/hub:4.3.0-20220706
    container_name: selenium-hub
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"

  scrapper:
    build: 
      dockerfile: Dockerfile
      context: .
    container_name: blaze_history_scrapper
    links:
      - selenium-hub:hub
    depends_on: 
      - selenium-hub
    volumes:
      - ./data/:/app/data/
    env_file:
      - .scrapper_env
    restart: always

  
